### ISSUE TITLE
No License

### ISSUE THREAD

**Issue by nightingale-m** [Dreamtowards/Ethertum#20]
I noticed there's no LICENSE file included. Without a license, users have no permission to use, modify, or share the code.

Some popular options include:
- MIT License
- Apache License 2.0
- GNU General Public License v3.0

You can also use the [Choose a License](https://choosealicense.com/) guide to help decide.

Thank you!

**Comment by Dreamtowards** [comment]
Thank you. I have initially chosen the GPL v3.0 license. My aim is to enable more interested individuals to share and collaborate together. However, I also want to prevent others from simply replacing or removing our names and information, claiming the work as their own, adding paid items, and making a lot of money, potentially even using that money to undermine us. I know this is a low-probability event, but it should be considered and guarded against.

Therefore, I have chosen the stricter GPL license, which helps with sharing, technical exchange, and collaborative development. It also ensures that anyone using my code must also open-source their work and acknowledge our contribution.

---

谢谢你。我初步选择了 GPL v3.0 协议。我的目的是，能够让更多感兴趣的人一起分享与合作。
但又想避免其他人拿我的代码 一键替换或删除我们的名字和信息，说是他自己做的，甚至在里面添加收费道具 大肆框揽钱财，甚至拿赚到的钱反过来打击我们。我知道这是小概率事件，但应该考虑到并设防。

因此我选择了较为严格的 GPL 协议，这有助于分享、技术交流与合作开发。同时其他人用我的代码后也要开源且著明出处 - 我们的信息。
